

class Constants {

  static List areas = <String>[
    'Hà Nội',
    'TP. Hồ Chí Minh',
    'Quảng Ninh',
    'Bắc Giang',
    'Lạng Sơn',
    'Cao Bằng',
    'Tuyên Quang',
    'Thái Nguyên',
    'Bắc Kạn',
    'Phú Thọ',
    'Vĩnh Phúc',
    'Sơn La',
    'Lai Châu',
    'Lào Cai',
    'Điện Biên',
    'Yên Bái',
    'Hòa Bình',
    'Hà Giang',
    'Hải Dương',
    'Hưng Yên',
    'Bắc Ninh',
    'Hải Phòng',
    'Hà Nam',
    'Thái Bình',
    'Nam Định',
    'Ninh Bình',
    'Quảng Bình',
    'Quảng Trị',
    'Thừa Thiên Huế',
    'Quảng Nam',
    'Đà Nẵng',
    'Thanh Hóa',
    'Nghệ An',
    'Hà Tĩnh',
    'Đồng Nai',
    'Bình Thuận',
    'Bà Rịa - Vũng Tàu',
    'Quảng Ngãi',
    'Bình Định',
    'Phú Yên',
    'Khánh Hòa',
    'Ninh Thuận',
    'Kon Tum',
    'Đắk Nông',
    'Đắk Lắk',
    'Lâm Đồng',
    'Gia Lai',
    'Vĩnh Long',
    'Bình Phước',
    'Long An',
    'Tiền Giang',
    'Bình Dương',
    'Bến Tre',
    'Tây Ninh',
    'Đồng Tháp',
    'Cà Mau',
    'Bạc Liêu',
    'Cần Thơ',
    'Hậu Giang',
    'Trà Vinh',
    'An Giang',
    'Kiên Giang',
    'Sóc Trăng',
    'Nước ngoài',
  ];

  static List occupations = <String>[
    'An toàn lao động',
    'Bán Hàng kỹ thuật',
    'Bán lẻ / bán sỉ',
    'Báo chí / Truyền hình',
    'Bảo hiểm',
    'Bảo trì / Sửa chữa',
    'Bất động sản',
    'Biên / Phiên dịch',
    'Bưu chính - Viễn thông',
    'Chứng khoán / Vàng / Ngoại tệ',
    'Cơ khí / Chế tạo / Tự động hóa',
    'Công nghệ cao',
    'Công nghệ ô tô',
    'Công nghệ thông tin',
    'Dầu khí / Hóa chất',
    'Dệt may / Da giày',
    'Địa chất / Khoáng sản',
    'Dịch vụ khách hàng',
    'Điện / Điện tử / Điện lạnh',
    'Điện tử viễn thông',
    'Du lịch',
    'Dược phẩm / Công nghệ sinh học',
    'Giáo dục / Đào tạo',
    'Hàng cao cấp',
    'Hàng gia dụng',
    'Hàng hải',
    'Hàng Không',
    'Hàng tiêu dùng',
    'Hành chính / Văn phòng',
    'Hóa học / Sinh học',
    'Hoạch định / Dự án',
    'In ấn / Xuất bản',
    'IT Phần cứng / Mạng',
    'IT Phần mềm',
    'Kế toán / Kiểm toán',
    'Khách sạn / Nhà hàng',
    'Kiến trúc',
    'Kinh doanh / Bán hàng',
    'Logistics',
    'Luật / Pháp lý',
    'Marketing / Truyền thông / Quảng cáo',
    'Môi trường / Xử lý chất thải',
    'Mỹ phẩm / Trang sức',
    'Mỹ thuật / Nghệ thuật / Điện ảnh',
    'Ngân hàng / Tài chính',
    'NGO / Phi chính phủ / Phi lợi nhuận',
    'Nhân sự',
    'Nông / Lâm / Ngư nghiệp',
    'Phi chính phủ / Phi lợi nhuận',
    'Quản lý chất lượng (QA/QC)',
    'Quản lý điều hành',
    'Sản phẩm công nghiệp',
    'Sản xuất',
    'Spa / Làm đẹp',
    'Tài chính / Đầu tư',
    'Thiết kế đồ họa',
    'Thiết kế nội thất',
    'Thời trang',
    'Thư ký / Trợ lý',
    'Thực phẩm / Đồ uống',
    'Tổ chức sự kiện / Quà tặng',
    'Tư vấn',
    'Vận tải / Kho vận',
    'Xây dựng',
    'Xuất nhập khẩu',
    'Y tế / Dược',
    'Ngành nghề khác',
  ];

  static List workingTypes = <String>[
    'Full time', 'Part time', 'Remote'
  ];

  static List experiences = <String>[
    'Chưa có kinh nghiệm', 'Dưới 1 năm', '1 năm', '2 năm', '3 năm', '4 năm', '5 năm', 'Trên 5 năm'
  ];

  static List positions = <String>[
    'Thực tập', 'Nhân viên', 'Trưởng nhóm', 'Trưởng/Phó Phòng', 'Quản lý / Giám sát', 'Trưởng chi nhánh', 'Phó giám đốc', 'Giám đốc' 
  ];

  static List industries = <String>[
    'Agency (Design/Development)',
    'Agency (Marketing/Advertising)',
    'Bán lẻ - Hàng tiêu dùng - FMCG',
    'Bảo hiểm',
    'Bảo trì / Sửa chữa',
    'Bất động sản',
    'Chứng khoán',
    'Cơ khí',
    'Cơ quan nhà nước',
    'Du lịch',
    'Dược phẩm / Y tế / Công nghệ sinh học',
    'Điện tử / Điện lạnh',
    'Giải trí',
    'Giáo dục / Đào tạo',
    'In ấn / Xuất bản',
    'Internet / Online',
    'IT - Phần cứng',
    'IT - Phần mềm',
    'Kế toán / Kiểm toán',
    'Logistic - Vận tải',
    'Luật',
    'Marketing / Truyền thông / Quảng cáo',
    'Môi trường',
    'Năng lượng',
    'Ngân hàng',
    'Nhà hàng / Khách sạn',
    'Nhân sự',
    'Nông lâm ngư nghiệp',
    'Sản xuất',
    'Tài chính',
    'Thiết kế / kiến trúc',
    'Thời trang',
    'Thương mại điện tử',
    'Tổ chức phi lợi nhuận',
    'Tự động hóa',
    'Tư vấn',
    'Viễn thông',
    'Xây dựng',
    'Xuất nhập khẩu',
    'Đa lĩnh vực',
  ];

}